name: Create file

on: [push]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create directory and create file
        run: |
          mkdir -p ./testfolder
          cd ./testfolder
          echo "Hello world! This is the file content." > file.txt

      - name: Commit and push new file
        run: |
          git add ./testfolder/file.txt
          git commit -m "Created file and pushed to branch"
          git push