name: Compile SASS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node packages
        run: npm install

      - name: Compile SASS to CSS
        run: npm run compile-sass
      
      - name: Commit Compiled CSS
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f *.css
          git commit -m "Compile SASS to CSS" || echo "No files to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
